# @package _global_

dataset:
  view_sampler:
    index_path: assets/evaluation_index_acid_video.json

evaluation:
  methods:
    - name: Ours
      key: ours
      path: baselines/acid/ours/frames_video
    - name: Du et al.
      key: du2023
      path: baselines/acid/yilun/frames_video
    - name: GPNR
      key: gpnr
      path: baselines/acid/gpnr/frames_video
    - name: pixelNeRF
      key: pixelnerf
      path: baselines/acid/pixelnerf/frames_video

  side_by_side_path: outputs/video/acid
  animate_side_by_side: true
  highlighted: []

output_metrics_path: outputs/video/acid/evaluation_metrics.json
