defaults:
  - dataset: nmr
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - model/encoder: epipolar
  - model/decoder: splatting_cuda
  - loss: [mse, density]

output_dir: null

wandb:
  project: pixelsplat
  entity: placeholder
  name: placeholder
  mode: offline

mode: train

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 16
    persistent_workers: true
    batch_size: 1
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 1.e-4
  warm_up_steps: 100
  cosine_lr: true

checkpointing:
  load: null
  every_n_train_steps: 10000
  save_top_k: -1

train:
  load_depth: null
  depth_mode: null
  extended_visualization: false

test:
  output_path: outputs/test

seed: 111123

strict: true

trainer:
  max_steps: -1
  val_check_interval: 5000
  # check_val_every_n_epoch: 1
  gradient_clip_val: 0.01
  prog_bar: True

model:
  encoder:
    # params for multi-view depth predictor
    unimatch_weights_path: "checkpoints/gmdepth-scale1-resumeflowthings-scannet-5d9d7964.pth"
    multiview_trans_attn_split: 2
    costvolume_unet_feat_dim: 128
    costvolume_unet_channel_mult: [1,1,1]
    costvolume_unet_attn_res: []
    depth_unet_feat_dim: 64
    depth_unet_attn_res: []
    depth_unet_channel_mult: [1, 1, 1]
    downscale_factor: 4
    shim_patch_size: 4

    # below are ablation settings, keep them as false for default model
    wo_depth_refine: false         # Table 3: base
    wo_cost_volume: false          # Table 3: w/o cost volume
    wo_backbone_cross_attn: false  # Table 3: w/o cross-view attention
    wo_cost_volume_refine: false   # Table 3: w/o U-Net
    use_epipolar_trans: false      # Table B: w/ Epipolar Transformer