defaults:
  - backbone: efficientnet

name: freesplat

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1

num_surfaces: 1

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 2

d_feature: 128

visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: false
