name: bounded

num_target_views: 1
num_context_views: 2

min_distance_between_context_views: 2
max_distance_between_context_views: 6
min_distance_to_context_views: 0

warm_up_steps: 0
initial_min_distance_between_context_views: 2
initial_max_distance_between_context_views: 6